name: gestra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  image_picker: ^0.8.9
  camera: ^0.10.5
  flutter_tflite: ^1.0.1
  permission_handler: ^10.2.0
  path: ^1.9.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  camera: ^0.10.5
  speech_to_text: ^7.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gestra.png
    - assets/model_sibi.tflite
    - assets/labels.txt